global:
  skip_to_content: 转跳到内容
  back_buttom: 返回
post_item:
  date: 创建于
  updated: 更新于
  notitle: 无标题
footer:
  frame: 框架
  theme: 主题
post:
  next_post: 下一篇文章
  prev_post: 上一篇文章
page:
  archives: 归档
  categories: 分类
  tags: 标签
  no_category: 暂无归类。
  no_tag: 暂无标签。
  no_archive: 暂无。
sidebar:
  site_info:
    title: 站点信息
    num_of_articles: 文章数目
    total_word_count: 总字数
    total_visitors: 总访客数
    total_visits: 总访问量
    runtime: 运行时长
    last_update: 最后更新时间