post_item:
  date: 创建于
  updated: 更新于
  notitle: 无标题
footer:
  frame: 框架
  theme: 主题
post:
  next_post: 下一篇文章
  prev_post: 上一篇文章
page:
  archive: 归档
  category: 分类
  tag: 标签
  no_category: 暂无归类。
  no_tag: 暂无标签。
  no_archive: 暂无。